name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x]

        steps:
            - uses: actions/checkout@v2

            - name: Configure node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Upgrade NPM
              run: npm install -g npm

            - name: Install dependencies
              run: npm ci

            - run: npm run build --if-present

            - run: npm test
